// Package robots renders a robots.txt from the same policy the edge enforces.
//
// The generator does not try to read CEL rules back into paths. Instead it asks
// the compiled policy engine what it would do for a synthetic request per bot
// and per candidate path, so the advisory file cannot disagree with enforcement
// by construction. Candidate paths are collected from the policy itself: the
// path-like strings in `sets` plus any path literal appearing in a rule.
package robots

import (
	"fmt"
	"sort"
	"strings"

	"github.com/jolovicdev/crawlwall/v2/internal/config"
	"github.com/jolovicdev/crawlwall/v2/internal/policy"
)

const header = "# Generated by crawlwall from the enforced policy. Do not edit by hand."

// Result is a rendered robots.txt plus anything the format could not express.
type Result struct {
	Body string

	// Warnings name rules whose outcome depends on inputs robots.txt has no way
	// to represent. They are the exact places where the advisory layer and the
	// edge can still disagree, so they are reported rather than hidden.
	Warnings []string
}

// group is one robots.txt record: the agents it covers and the directives they
// share.
type group struct {
	agents     []string
	disallow   []string
	allow      []string
	crawlDelay int
	wildcard   bool
}

// Generate renders robots.txt for cfg. It returns an error only if the policy
// itself fails to compile or evaluate, which makes generation a policy lint too.
func Generate(cfg *config.Config) (Result, error) {
	engine, err := policy.NewEngine(cfg)
	if err != nil {
		return Result{}, err
	}

	paths := candidatePaths(cfg)

	groups := make([]group, 0, len(cfg.Bots))
	for _, botCfg := range cfg.Bots {
		built, err := buildGroup(cfg, engine, botCfg, paths)
		if err != nil {
			return Result{}, err
		}
		if len(built.agents) > 0 {
			groups = append(groups, built)
		}
	}

	return Result{
		Body:     render(cfg, mergeGroups(groups)),
		Warnings: warnings(cfg),
	}, nil
}

func buildGroup(cfg *config.Config, engine *policy.Engine, botCfg config.BotConfig, paths []string) (group, error) {
	built := group{
		agents:   agentsFor(botCfg),
		wildcard: botCfg.Match.Default,
	}
	if len(built.agents) == 0 {
		return built, nil
	}

	blocked := make(map[string]bool, len(paths))
	for _, path := range paths {
		decision, err := engine.Evaluate(inputFor(cfg, engine, botCfg, path))
		if err != nil {
			return group{}, fmt.Errorf("evaluate %s for bot %s: %w", path, botCfg.ID, err)
		}
		blocked[path] = decision.Action.Type == config.ActionBlock

		// Crawl-delay is per group, not per path, so the most restrictive limit
		// any path implies is the one advertised.
		if decision.Action.Type == config.ActionRateLimit && decision.Action.Limit != nil {
			if delay := crawlDelaySeconds(decision.Action.Limit.RPM); delay > built.crawlDelay {
				built.crawlDelay = delay
			}
		}
	}

	built.disallow, built.allow = directives(paths, blocked)
	return built, nil
}

// directives reduces per-path verdicts to the shortest set of lines that says
// the same thing. Crawlers resolve overlapping rules by longest match, so a
// path only needs a line when its verdict differs from the closest rule already
// covering it. That turns "block everything, allow one carve-out" into two
// lines instead of one per probed path.
func directives(paths []string, blocked map[string]bool) (disallow, allow []string) {
	for _, path := range paths {
		ancestor, hasAncestor := closestPrefix(paths, path)

		switch {
		case !hasAncestor:
			// Nothing covers this path. Allowing is already the default, so
			// only a block is worth stating.
			if blocked[path] {
				disallow = append(disallow, path)
			}
		case blocked[path] == blocked[ancestor]:
			// Already implied by the covering rule.
		case blocked[path]:
			disallow = append(disallow, path)
		default:
			allow = append(allow, path)
		}
	}

	// Probing order is shortest-first; reading order is alphabetical.
	sort.Strings(disallow)
	sort.Strings(allow)
	return disallow, allow
}

// closestPrefix returns the longest other path that robots.txt prefix-matching
// would apply to path.
func closestPrefix(paths []string, path string) (string, bool) {
	best := ""
	for _, candidate := range paths {
		if candidate == path || !strings.HasPrefix(path, candidate) {
			continue
		}
		if len(candidate) > len(best) {
			best = candidate
		}
	}
	return best, best != ""
}

// inputFor builds the policy input for a bot fetching path.
//
// Two assumptions are baked in and worth stating. The request is a plain GET
// with no query, because that is what a crawler fetching a URL does. And a bot
// with a verifier is evaluated as verified, because robots.txt speaks to the
// honest crawler; an impostor is the edge's problem, not the advisory file's.
// A bot with `verify.type: none` is evaluated unverified, matching runtime.
func inputFor(cfg *config.Config, engine *policy.Engine, botCfg config.BotConfig, path string) policy.Input {
	userAgent := botCfg.Name
	if len(botCfg.Match.UserAgents) > 0 {
		userAgent = botCfg.Match.UserAgents[0]
	}

	return policy.Input{
		Bot: policy.BotInput{
			ID:       botCfg.ID,
			Name:     botCfg.Name,
			Class:    botCfg.Class,
			Claimed:  !botCfg.Match.Default,
			Verified: botCfg.Verify.Type != "none" && botCfg.Verify.Type != "",
			Operator: botCfg.Operator,
		},
		Request: policy.RequestInput{
			Host:      cfg.Site.Host,
			Method:    "GET",
			Path:      path,
			IP:        "",
			UserAgent: userAgent,
			Headers:   map[string]string{},
		},
		Site:   engine.SiteInput(),
		Sets:   engine.SetsInput(),
		Labels: policy.LabelsFor(botCfg.ID, cfg.Site.Host, path),
	}
}

// agentsFor returns the robots.txt product tokens for a bot. The user-agent
// needles the edge matches on are reused, so the two layers key off the same
// strings.
func agentsFor(botCfg config.BotConfig) []string {
	if botCfg.Match.Default {
		return []string{"*"}
	}

	agents := make([]string, 0, len(botCfg.Match.UserAgents))
	for _, needle := range botCfg.Match.UserAgents {
		if needle = strings.TrimSpace(needle); needle != "" {
			agents = append(agents, needle)
		}
	}
	return agents
}

// crawlDelaySeconds converts a per-minute limit into the seconds between
// requests a crawler should wait, rounded up so a compliant crawler stays under
// the limit rather than at it.
func crawlDelaySeconds(rpm int) int {
	if rpm <= 0 || rpm >= 60 {
		return 0
	}
	return (60 + rpm - 1) / rpm
}

// mergeGroups folds bots with identical directives into one record. The
// wildcard group stays separate and last, which is both conventional and easier
// to read than finding `*` buried among named agents.
func mergeGroups(groups []group) []group {
	merged := make([]group, 0, len(groups))
	index := map[string]int{}
	var wildcard *group

	for _, candidate := range groups {
		if candidate.wildcard {
			entry := candidate
			wildcard = &entry
			continue
		}

		key := signature(candidate)
		if at, ok := index[key]; ok {
			merged[at].agents = append(merged[at].agents, candidate.agents...)
			continue
		}
		index[key] = len(merged)
		merged = append(merged, candidate)
	}

	sort.SliceStable(merged, func(i, j int) bool { return merged[i].agents[0] < merged[j].agents[0] })
	if wildcard != nil {
		merged = append(merged, *wildcard)
	}
	return merged
}

func signature(g group) string {
	return fmt.Sprintf("%d|%s|%s", g.crawlDelay, strings.Join(g.disallow, ","), strings.Join(g.allow, ","))
}

func render(cfg *config.Config, groups []group) string {
	var out strings.Builder
	out.WriteString(header)
	out.WriteString("\n")

	if cfg.Site.Mode != config.SiteModeEnforce {
		fmt.Fprintf(&out, "# Site mode is %q, so these rules are not currently enforced at the edge.\n", cfg.Site.Mode)
	}

	for _, g := range groups {
		out.WriteString("\n")
		for _, agent := range g.agents {
			fmt.Fprintf(&out, "User-agent: %s\n", agent)
		}

		for _, path := range g.disallow {
			fmt.Fprintf(&out, "Disallow: %s\n", path)
		}
		for _, path := range g.allow {
			fmt.Fprintf(&out, "Allow: %s\n", path)
		}
		if len(g.disallow) == 0 {
			// The canonical way to say "nothing is off limits".
			out.WriteString("Disallow:\n")
		}

		if g.crawlDelay > 0 {
			fmt.Fprintf(&out, "Crawl-delay: %d\n", g.crawlDelay)
		}
	}

	for _, sitemap := range cfg.Robots.Sitemaps {
		if sitemap = strings.TrimSpace(sitemap); sitemap != "" {
			fmt.Fprintf(&out, "\nSitemap: %s\n", sitemap)
		}
	}

	return out.String()
}

// nonRepresentable maps a policy input that robots.txt cannot express onto the
// reason it cannot. bot.verified is deliberately absent: it is pinned by
// inputFor and documented there rather than warned about on every run.
var nonRepresentable = []struct{ reference, why string }{
	{"request.method", "robots.txt cannot vary by HTTP method"},
	{"request.query", "robots.txt matches paths, and query strings only via wildcards crawlers honor inconsistently"},
	{"request.ip", "robots.txt cannot vary by client address"},
	{"request.headers", "robots.txt cannot vary by request header"},
	{"request.host", "robots.txt is served per host, so a host-dependent rule needs one file per host"},
	{"labels.", "robots.txt cannot vary by computed label"},
}

// warnings reports every rule whose outcome depends on something the format
// cannot carry. These are the only places the two layers can still disagree, so
// they are surfaced rather than silently approximated.
//
// Every rule is checked, not only the ones that decided a probe. A rule gated
// on `request.method == "POST"` never wins for the synthetic GET used here, and
// that is exactly why it needs reporting: it is invisible in the output while
// still being enforced at the edge.
func warnings(cfg *config.Config) []string {
	var out []string
	for _, rule := range cfg.Rules {
		for _, limit := range nonRepresentable {
			if strings.Contains(rule.When, limit.reference) {
				out = append(out, fmt.Sprintf("rule %q depends on %s: %s", rule.ID, limit.reference, limit.why))
			}
		}
	}
	return out
}

// candidatePaths collects the paths worth probing: the root, every path-like
// string in `sets`, and every path literal written inline in a rule. Adding a
// path only widens what is probed, never changes an answer, so missing one
// makes the file less complete rather than wrong.
func candidatePaths(cfg *config.Config) []string {
	found := map[string]struct{}{"/": {}}

	collectPaths(cfg.Sets, found)
	for _, rule := range cfg.Rules {
		for _, literal := range stringLiterals(rule.When) {
			if strings.HasPrefix(literal, "/") {
				found[literal] = struct{}{}
			}
		}
	}

	paths := make([]string, 0, len(found))
	for path := range found {
		paths = append(paths, path)
	}
	// Shortest first so prefixes are decided before the paths they cover, and
	// alphabetically within a length for stable output.
	sort.Slice(paths, func(i, j int) bool {
		if len(paths[i]) != len(paths[j]) {
			return len(paths[i]) < len(paths[j])
		}
		return paths[i] < paths[j]
	})
	return paths
}

func collectPaths(value any, found map[string]struct{}) {
	switch typed := value.(type) {
	case map[string]any:
		for _, item := range typed {
			collectPaths(item, found)
		}
	case []any:
		for _, item := range typed {
			collectPaths(item, found)
		}
	case string:
		if strings.HasPrefix(typed, "/") {
			found[typed] = struct{}{}
		}
	}
}

// stringLiterals pulls quoted strings out of a CEL expression. It is a
// heuristic used only to widen the probe set, never to decide an outcome.
func stringLiterals(expression string) []string {
	var literals []string
	for i := 0; i < len(expression); i++ {
		quote := expression[i]
		if quote != '"' && quote != '\'' {
			continue
		}
		if end := strings.IndexByte(expression[i+1:], quote); end >= 0 {
			literals = append(literals, expression[i+1:i+1+end])
			i += end + 1
		}
	}
	return literals
}
