package robots

import (
	"strings"
	"testing"

	"github.com/jolovicdev/crawlwall/v2/internal/config"
	"github.com/jolovicdev/crawlwall/v2/internal/policy"
)

func TestGenerateDerivesGroupsFromPolicy(t *testing.T) {
	result, err := Generate(testConfig())
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	want := strings.TrimSpace(`
# Generated by crawlwall from the enforced policy. Do not edit by hand.

User-agent: GPTBot
Disallow: /archive
Disallow: /datasets
Crawl-delay: 6

User-agent: Googlebot
Disallow:

User-agent: *
Disallow: /
Allow: /public
`)

	if got := strings.TrimSpace(result.Body); got != want {
		t.Fatalf("Generate() body =\n%s\n\nwant:\n%s", got, want)
	}
}

// The point of generating from policy is that the two layers cannot disagree.
// This walks every group and path in the rendered file and asserts the engine
// makes the matching decision.
func TestGeneratedFileAgreesWithPolicyEngine(t *testing.T) {
	cfg := testConfig()
	result, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	engine, err := policy.NewEngine(cfg)
	if err != nil {
		t.Fatalf("NewEngine() error = %v", err)
	}

	botsByAgent := map[string]config.BotConfig{}
	for _, botCfg := range cfg.Bots {
		for _, agent := range agentsFor(botCfg) {
			botsByAgent[agent] = botCfg
		}
	}

	var current config.BotConfig
	var haveBot bool
	for _, line := range strings.Split(result.Body, "\n") {
		directive, value, found := strings.Cut(line, ":")
		if !found {
			continue
		}
		value = strings.TrimSpace(value)

		switch directive {
		case "User-agent":
			current, haveBot = botsByAgent[value]
			if !haveBot {
				t.Fatalf("robots.txt names agent %q with no matching bot", value)
			}
		case "Disallow", "Allow":
			if !haveBot || value == "" {
				continue
			}
			decision, err := engine.Evaluate(inputFor(cfg, engine, current, value))
			if err != nil {
				t.Fatalf("Evaluate(%s) error = %v", value, err)
			}

			blocked := decision.Action.Type == config.ActionBlock
			if blocked != (directive == "Disallow") {
				t.Fatalf("%s: %s for bot %s, but the policy says %s (rule %s)",
					directive, value, current.ID, decision.Action.Type, decision.RuleID)
			}
		}
	}
}

func TestGenerateWarnsAboutInexpressibleRules(t *testing.T) {
	cfg := testConfig()
	cfg.Rules = append(cfg.Rules, config.RuleConfig{
		ID:       "block_post_to_archive",
		Priority: 5,
		When:     `request.method == "POST" && request.path.startsWith("/archive")`,
		Action:   config.Action{Type: config.ActionBlock, Status: 403, Reason: "no_writes"},
	})

	result, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if len(result.Warnings) == 0 {
		t.Fatalf("expected a warning: a method-dependent rule cannot be expressed in robots.txt")
	}
	if !strings.Contains(result.Warnings[0], "request.method") {
		t.Fatalf("warning = %q, want it to name request.method", result.Warnings[0])
	}
}

func TestGenerateNotesNonEnforcingMode(t *testing.T) {
	cfg := testConfig()
	cfg.Site.Mode = config.SiteModeShadow

	result, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if !strings.Contains(result.Body, "not currently enforced") {
		t.Fatalf("shadow mode should be disclosed in the file, got:\n%s", result.Body)
	}
}

func TestGenerateEmitsSitemaps(t *testing.T) {
	cfg := testConfig()
	cfg.Robots.Sitemaps = []string{"https://example.test/sitemap.xml"}

	result, err := Generate(cfg)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}
	if !strings.Contains(result.Body, "Sitemap: https://example.test/sitemap.xml") {
		t.Fatalf("missing sitemap line in:\n%s", result.Body)
	}
}

func TestGenerateSurfacesBrokenPolicy(t *testing.T) {
	cfg := testConfig()
	cfg.Rules = append(cfg.Rules, config.RuleConfig{
		ID:     "not_a_predicate",
		When:   `request.path`,
		Action: config.Action{Type: config.ActionAllow},
	})

	// Generation evaluates the real engine, so it doubles as a policy lint.
	if _, err := Generate(cfg); err == nil {
		t.Fatalf("Generate() error = nil, want the non-boolean rule to surface")
	}
}

func TestCandidatePathsComeFromSetsAndRuleLiterals(t *testing.T) {
	paths := candidatePaths(&config.Config{
		Sets: map[string]any{"protected": []any{"/archive", "/datasets"}},
		Rules: []config.RuleConfig{
			{ID: "inline", When: `request.path.startsWith("/admin")`},
			{ID: "noise", When: `bot.class == "search"`},
		},
	})

	want := map[string]bool{"/": true, "/admin": true, "/archive": true, "/datasets": true}
	if len(paths) != len(want) {
		t.Fatalf("candidatePaths() = %v, want exactly %v", paths, want)
	}
	for _, path := range paths {
		if !want[path] {
			t.Fatalf("candidatePaths() returned unexpected %q", path)
		}
	}
	if paths[0] != "/" {
		t.Fatalf("candidatePaths()[0] = %q, want the root first so prefixes resolve before what they cover", paths[0])
	}
}

func TestCrawlDelayOnlyWhenSlowerThanOnePerSecond(t *testing.T) {
	for _, tc := range []struct {
		rpm  int
		want int
	}{
		{rpm: 10, want: 6},
		{rpm: 7, want: 9}, // rounded up, so a compliant crawler stays under the limit
		{rpm: 60, want: 0},
		{rpm: 120, want: 0},
		{rpm: 0, want: 0},
	} {
		if got := crawlDelaySeconds(tc.rpm); got != tc.want {
			t.Fatalf("crawlDelaySeconds(%d) = %d, want %d", tc.rpm, got, tc.want)
		}
	}
}

// testConfig exercises the interesting shapes: an unrestricted bot, a bot with
// blocked paths and a sub-minute rate limit, and a default group that is denied
// everything except one carve-out.
func testConfig() *config.Config {
	return &config.Config{
		Version: config.VersionV1,
		Site:    config.SiteConfig{ID: "test", Host: "example.test", Mode: config.SiteModeEnforce},
		Runtime: config.RuntimeConfig{
			FailMode:      config.FailModeBlock,
			DefaultAction: config.Action{Type: config.ActionAllow},
		},
		Sets: map[string]any{
			"protected": []any{"/archive", "/datasets"},
			"open":      []any{"/public"},
		},
		Bots: []config.BotConfig{
			{
				ID: "googlebot", Name: "Googlebot", Class: "search",
				Match:  config.MatchConfig{UserAgents: []string{"Googlebot"}},
				Verify: config.VerifyConfig{Type: "reverse_dns", AllowedSuffixes: []string{".googlebot.com"}},
			},
			{
				ID: "gptbot", Name: "GPTBot", Class: "ai_training",
				Match:  config.MatchConfig{UserAgents: []string{"GPTBot"}},
				Verify: config.VerifyConfig{Type: "ip_ranges", Sources: []string{"https://openai.com/gptbot.json"}},
			},
			{
				ID: "unknown", Name: "Unknown", Class: "unknown",
				Match:  config.MatchConfig{Default: true},
				Verify: config.VerifyConfig{Type: "none"},
			},
		},
		Rules: []config.RuleConfig{
			{
				ID: "allow_search", Priority: 100,
				When:   `bot.verified && bot.class == "search"`,
				Action: config.Action{Type: config.ActionAllow},
			},
			{
				ID: "block_training_from_protected", Priority: 200,
				When:   `bot.class == "ai_training" && sets.protected.exists(p, request.path.startsWith(p))`,
				Action: config.Action{Type: config.ActionBlock, Status: 403, Reason: "no_training"},
			},
			{
				ID: "rate_limit_training", Priority: 300,
				When: `bot.class == "ai_training"`,
				Action: config.Action{
					Type:  config.ActionRateLimit,
					Limit: &config.Limit{Key: "bot.id", RPM: 10},
				},
			},
			{
				ID: "allow_unknown_public", Priority: 800,
				When:   `bot.class == "unknown" && request.path.startsWith("/public")`,
				Action: config.Action{Type: config.ActionAllow},
			},
			{
				ID: "block_unknown", Priority: 900,
				When:   `bot.class == "unknown"`,
				Action: config.Action{Type: config.ActionBlock, Status: 403, Reason: "unknown_crawler"},
			},
		},
	}
}
